branches:
  only:
  - develop
  - master
  - /^release-.*$/
  - /^hotfix-.*$/

language: bash

services:
  - docker

before_install:
  - sudo pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    export ES_ENV_HOST="search-uvaedplatform-staging-mvlcxpy4wbc3csxju6cccbsmzy.us-east-1.es.amazonaws.com" || exit 1 ;
    export BUILD_ENV="dev" || exit 1 ;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    export ES_ENV_HOST="search-uvaedplatform-wnme5klsj632ii3zr5hgho46cu.us-east-1.es.amazonaws.com" || exit 1 ;
    export BUILD_ENV="prod" || exit 1 ;
    else
    export ES_ENV_HOST="search-uvaedplatform-staging-mvlcxpy4wbc3csxju6cccbsmzy.us-east-1.es.amazonaws.com" || exit 1 ;
    export BUILD_ENV="uat" || exit 1 ;    
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    export GIT_TAG=prod-1.0 || exit 1 ;
    docker build --build-arg BUILD_ENV --build-arg ES_ENV_HOST -f docker/Dockerfile --no-cache -t ithriv/ithriv_service:"$GIT_TAG" . || exit 1 ;
    docker push ithriv/ithriv_service:"$GIT_TAG" || exit 1 ;
    docker tag ithriv/ithriv_service:"$GIT_TAG" ithriv/ithriv_service:latest || exit 1 ;
    docker push ithriv/ithriv_service:latest || exit 1 ;
    git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER" || exit 1 ; 
    git push origin $GIT_TAG
    else
    docker build --build-arg BUILD_ENV --build-arg ES_ENV_HOST -f docker/Dockerfile --no-cache -t ithriv/ithriv_service:"$TRAVIS_BRANCH" . || exit 1 ;
    docker push ithriv/ithriv_service:"$TRAVIS_BRANCH" || exit 1 ;
    aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/ithriv-updates' --message-body ithriv/ithriv_service:$TRAVIS_BRANCH || exit 1;
    fi


notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - rkc7h@virginia.edu