branches:
  only:
  - master
  - staging
  - dev

language: bash

services:
  - docker

before_install:
  - sudo pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -f docker/Dockerfile --no-cache -t ithriv/ithriv_service:latest . || exit 1 ;
    docker push ithriv/ithriv_service:latest || exit 1 ;
    fi


notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - rkc7h@virginia.edu